name: cdk-github-actions
run-name: Action cdk deploy when pushing to main branch
on:
  push:
    branches:
      - main
jobs:
  cdk-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: '18'
